### ISSUE TITLE
Dockerize the Django app

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/trade-motors#1]
Create a minimal Docker container to make development easier and toward continuous delivery.

- [x] Minimal Docker container (Maybe alpine)
- [x] docker-compose.yml which links to mysql container, i.e. App container connects to mysql container

**Comment by emman27** [comment]
Could I take this up?

**Comment by angelbarrera92** [comment]
I have it!
I will do a PR in a few minutes. 
I used a basic python image (not alpine one because some errors installing some dependencies).

**Comment by angelbarrera92** [comment]
I have solved this issue on #7 
I hope any news from you!
