### ISSUE TITLE
CI Integration with Travis

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/trade-motors#3]
- [x] Run Tests on Travis
- [x] Add a status badge in README.md

**Comment by Jtramey** [comment]
@haroon-sheikh I should be able to take care of this one pretty quickly, if that's alright?

**Comment by haroon-sheikh** [comment]
@Jtramey I'm happy for you to pick this up for the initial solution. 

But we might need to revisit this after https://github.com/sitture/trade-motors/issues/1 is complete.

**Comment by Jtramey** [comment]
I'll just start with number 1 this evening.

**Comment by haroon-sheikh** [comment]
I'd really appreciate your help.
