### ISSUE TITLE
Modify dockerfile to support running tests.

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/trade-motors#31]
Currently the tests are run when building the image.

We should be able to use the `docker run` command to run the tests when needed:

E.g. `docker run -d -p 8000:8000 trade-motors:0.1.0 python manage.py test`

**Comment by willBoyd8** [comment]
It seems like you can already run tests with `docker run -p 8000:8000 trade-motors:0.1.0 python manage.py test`. All that's required is to drop the `-d` (`--detach`) to see their output. This also works with `docker run trade-motors:0.1.0 python manage.py test` (no port is needed to run the tests). You could add a `test` script to run the tests with `docker run trade-motors:0.1.0 test` in celebration of `hacktoberfest`...

**Comment by haroon-sheikh** [comment]
@willBoyd8 will you be able to add a line in README (within the docker section) explaining how to run tests ;)

**Comment by willBoyd8** [comment]
Done! See https://github.com/sitture/trade-motors/pull/37
